### ISSUE TITLE
unknown log level: warn

### ISSUE THREAD

**Issue by seriousManual** [RiptideCloud/winston-logentries-transport#1]
the logentries backend only accepts the keywords 'warning' and 'err' as log levels whereas winston assignes 'warn' and 'error'.
these logentries are dropped, not something one would expect...

**Comment by markstos** [comment]
Something like the "levelMapping" in rsyslog2 may be of interest: https://github.com/imsky/winston-rsyslog2

**Comment by DavidTPate** [comment]
This is not something I've been able to reproduce. I'm using this in conjunction with log entries right now and all of my log levels properly display in LogEntries. Whether they are `error`, `warn`, `debug`, `info`, or my personal-all-time-favorite (stolen from Android) `wtf` (aka "What a Terrible Failure").

**Comment by seriousManual** [comment]
it may have been fixed on logentrie's serverside now.
