### ISSUE TITLE
Is the NPM documentation out of date?

### ISSUE THREAD

**Issue by light24bulbs** [RiptideCloud/winston-logentries-transport#2]
It differs from the github documentation.  Also, it doesn't work if configured that way. https://github.com/RiptideCloud/winston-logentries-transport

**Comment by DavidTPate** [comment]
I took a look at our [NPM page](https://www.npmjs.com/package/winston-logentries-transport) and things are looking like I expect them. I also gave it a try in some of the places that we use it and didn't hit any issues.

Looking at [Logentries](https://www.npmjs.com/package/logentries) I see that they link to another transport called [Winston Logentries](https://www.npmjs.com/package/winston-logentries) were you by chance meaning to find that one?

Either way, if you want to put up a code example, I'd be glad to help out.

**Comment by markstos** [comment]
It appears that this issue can be closed.

**Comment by DavidTPate** [comment]
Yeah, I'm thinking so. Re-open if you are still having issues @light24bulbs .
